create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Skater',
  skating_start_date date not null default current_date,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id text primary key,
  name text not null,
  description text not null default '',
  stat text not null check (stat in ('skill', 'body', 'mind', 'discipline', 'recovery', 'character')),
  xp integer not null check (xp > 0),
  active boolean not null default true,
  frequency text not null default 'daily' check (frequency = 'daily'),
  created_at timestamptz not null default now()
);

create table if not exists public.daily_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  task_id text not null references public.tasks(id) on delete restrict,
  completion_date date not null,
  xp_awarded integer not null check (xp_awarded > 0),
  completed_at timestamptz not null default now(),
  unique (user_id, task_id, completion_date)
);

create table if not exists public.quests (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  target_hours numeric not null default 100 check (target_hours > 0),
  completed_hours numeric not null default 0 check (completed_hours >= 0),
  status text not null default 'active' check (status in ('active', 'completed')),
  started_at date not null default current_date,
  completed_at timestamptz,
  completion_bonus_xp integer not null default 2000 check (completion_bonus_xp >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.skate_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_date date not null default current_date,
  hours numeric not null check (hours > 0),
  created_at timestamptz not null default now()
);

insert into public.tasks (id, name, description, stat, xp)
values
  ('skate', 'Skate', 'Deliberate skate practice', 'skill', 500),
  ('strength', 'Strength / Body', 'Physical training and conditioning', 'body', 250),
  ('mobility', 'Mobility', 'Mobility and recovery flow', 'body', 150),
  ('mind', 'Mind', 'Footage review and reflection', 'mind', 150),
  ('japanese', 'Japanese', 'Language and intentional study', 'discipline', 150),
  ('recovery', 'Recovery', 'Sleep, food, rest, and care', 'recovery', 150),
  ('character', 'Character', 'One intentional act of kindness', 'character', 150)
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;
alter table public.daily_completions enable row level security;
alter table public.quests enable row level security;
alter table public.skate_sessions enable row level security;

drop policy if exists "Users can view their profile" on public.profiles;
create policy "Users can view their profile" on public.profiles for select using (auth.uid() = id);
drop policy if exists "Users can insert their profile" on public.profiles;
create policy "Users can insert their profile" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile" on public.profiles for update using (auth.uid() = id);

drop policy if exists "Anyone can view active tasks" on public.tasks;
create policy "Anyone can view active tasks" on public.tasks for select using (active = true);

drop policy if exists "Users can view their completions" on public.daily_completions;
create policy "Users can view their completions" on public.daily_completions for select using (auth.uid() = user_id);
drop policy if exists "Users can create their completions" on public.daily_completions;
create policy "Users can create their completions" on public.daily_completions for insert with check (auth.uid() = user_id);

drop policy if exists "Users can view their quests" on public.quests;
create policy "Users can view their quests" on public.quests for select using (auth.uid() = user_id);
drop policy if exists "Users can create their quests" on public.quests;
create policy "Users can create their quests" on public.quests for insert with check (auth.uid() = user_id);
drop policy if exists "Users can update their quests" on public.quests;
create policy "Users can update their quests" on public.quests for update using (auth.uid() = user_id);

drop policy if exists "Users can view their skate sessions" on public.skate_sessions;
create policy "Users can view their skate sessions" on public.skate_sessions for select using (auth.uid() = user_id);
drop policy if exists "Users can create their skate sessions" on public.skate_sessions;
create policy "Users can create their skate sessions" on public.skate_sessions for insert with check (auth.uid() = user_id);
